version: '3.8'

services:
  app:
    image: ticketapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketapp
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    networks:
      - db-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ticket_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  mysql-db:
    image: mysql:8.0
    container_name: ticketapp
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: ticket_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - db-network

volumes:
  mysql-data:

networks:
  db-network: